ERR_CODES = {
    '0x10': ('CommandSuccess', 'Command succeeded.'),
    '0x11': ('command_fail', 'Command failed.'),
    '0x20': ('mcu_reset_error', 'CPU reset error.'),
    '0x21': ('cw_on_error', 'Turn on CW error.48'),
    '0x22': ('antenna_missing_error', 'Antenna is missing.'),
    '0x23': ('write_flash_error', 'Write flash error.'),
    '0x24': ('read_flash_error', 'Read flash error.'),
    '0x25': ('set_output_power_error', 'Set output power error.'),
    '0x31': ('tag_inventory_error', 'Error occurred when inventory.'),
    '0x32': ('tag_read_error', 'Error occurred when read.'),
    '0x33': ('tag_write_error', 'Error occurred when write.'),
    '0x34': ('tag_lock_error', 'Error occurred when lock.'),
    '0x35': ('tag_kill_error', 'Error occurred when kill.'),
    '0x36': ('no_tag_error', 'There is no tag to be operated.'),
    '0x37': ('inventory_ok_but_access_fail', 'Tag Inventoried but access failed.'),
    '0x38': ('buffer_is_empty_error', 'Buffer is empty.'),
    '0x40': ('access_or_password_error', 'Access failed or wrong password.'),
    '0x41': ('parameter_invalid', 'Invalid parameter.'),
    '0x42': ('parameter_invalid_wordCnt_too_long', 'WordCnt is too long.'),
    '0x43': ('parameter_invalid_membank_out_of_range', 'MemBank out of range.'),
    '0x44': ('parameter_invalid_lock_region_out_of_range', 'Lock region out of range.'),
    '0x45': ('parameter_invalid_lock_action_out_of_range', 'LockType out of range.'),
    '0x46': ('parameter_reader_address_invalid', 'Invalid reader address.'),
    '0x47': ('parameter_invalid_AntennaID_out_of_range', 'AntennaID out of range.'),
    '0x48': ('parameter_invalid_output_power_out_of_range', 'Output power out of range.'),
    '0x49': ('parameter_invalid_frequency_region_out_of_range', 'Frequency region out of range.'),
    '0x50': ('fail_to_get_RN16_from_tag', 'Failed to receive RN16 from tag.'),
    '0x51': ('parameter_invalid_drm_mode', 'Invalid DRM mode.'),
    '0x52': ('pll_lock_fail', 'PLL can not lock.'),
    '0x53': ('rf_chip_fail_to_response', 'No response from RF chip.'),
    '0x54': ('fail_to_achieve_desired_output_power', 'Can’t achieve desired output power level.'),
    '0x55': ('copyright_authentication_fail', 'Can’t authenticate firmware copyright.'),
    '0x56': ('spectrum_regulation_error', 'Spectrum regulation wrong.'),
    '0x57': ('output_power_too_low', 'Output power is too low.')
}
